import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Olaksaj.se</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>Tema danas:</h2>
        <p>Lorem ipsum dolor sit amet</p>
        <textarea className={styles.message} rows={10}></textarea>
      </main>
    </>
  );
}
